baseURL = 'https://pippyjames.pizza/'
languageCode = 'en-gb'
title = 'Pippy James'
theme = "hermit"

[author]
  name = "Sam Briggs"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  homeSubtitle = "Taking over the world, one marinara at a time 🍕"
